/**
 * @file EVE_MCU_STM32.c
 * @details MCU-specific code for controlling EVE on STM32 devices.
 */
/*
 * ============================================================================
 * (C) Copyright,  Bridgetek Pte. Ltd.
 * ============================================================================
 *
 * This source code ("the Software") is provided by Bridgetek Pte Ltd
 * ("Bridgetek") subject to the licence terms set out
 * http://brtchip.com/BRTSourceCodeLicenseAgreement/ ("the Licence Terms").
 * You must read the Licence Terms before downloading or using the Software.
 * By installing or using the Software you agree to the Licence Terms. If you
 * do not agree to the Licence Terms then do not download or use the Software.
 *
 * Without prejudice to the Licence Terms, here is a summary of some of the key
 * terms of the Licence Terms (and in the event of any conflict between this
 * summary and the Licence Terms then the text of the Licence Terms will
 * prevail).
 *
 * The Software is provided "as is".
 * There are no warranties (or similar) in relation to the quality of the
 * Software. You use it at your own risk.
 * The Software should not be used in, or for, any medical device, system or
 * appliance. There are exclusions of Bridgetek liability for certain types of loss
 * such as: special loss or damage; incidental loss or damage; indirect or
 * consequential loss or damage; loss of income; loss of business; loss of
 * profits; loss of revenue; loss of contracts; business interruption; loss of
 * the use of money or anticipated savings; loss of information; loss of
 * opportunity; loss of goodwill or reputation; and/or loss of, damage to or
 * corruption of data.
 * There is a monetary cap on Bridgetek's liability.
 * The Software may have subsequently been amended by another user and then
 * distributed by that other user ("Adapted Software").  If so that user may
 * have additional licence terms that apply to those amendments. However, Bridgetek
 * has no liability in relation to those amendments.
 * ============================================================================
 */

// Guard against being used for incorrect platform or architecture.
#if defined(PLATFORM_STM32)

#pragma message "Compiling " __FILE__ " for ST STM32"

/* EVE MCU HEADER */

#define bswap16(x) (((x) >> 8) | ((x) << 8))
#define bswap32(x) (((x) >> 24) | (((x) & 0x00FF0000) >> 8) \
                  | (((x) & 0x0000FF00) << 8) | ((x) << 24))

/* Header for STM32 (generated by STMCubeMX) */
#include <main.h>

#include <string.h>
#include <stdint.h> // For Uint8/16/32 and Int8/16/32 data types
// Note there is no endian.h for this platform.

/* Include functions for EVE-MCU-Dev library MCU layer */
#include <MCU.h>

/* EVE MCU HEADER END */

/* EVE MCU */

// This is the STM32 platform specific section and contains the functions which
// enable the GPIO and SPI interfaces.

extern GPIO_TypeDef *config_gpio;
extern uint16_t config_pin_pd;
extern uint16_t config_pin_cs;
extern uint16_t config_pin_int;

/* SPI handler declaration */
extern SPI_HandleTypeDef hspi1;

int MCU_Init(void)
{
    /* Set the SPI speed to a safe minimum. It must be
     * under 11 MHz but 1 MHz is very safe.
     * Use the "safe" prescaler to get a safe clock for SPI
     * during initialisation.
     */
    hspi1.Init.NSS = SPI_NSS_SOFT;
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32;
    if (HAL_SPI_Init(&hspi1) != HAL_OK)
    {
        /* Initialization Error */
        Error_Handler();
        return -1;
    }

    return 0;
}

int MCU_Deinit(void)
{
    /* Leave EVE in a safe state. */
    MCU_CShigh();
    MCU_PDlow();

    /* Disable SPI peripheral. */
    if (HAL_SPI_DeInit(&hspi1) != HAL_OK)
    {
        return -1;
    }

    return 0;
}

int MCU_Setup(void)
{
    /* Additional SPI Configuration */
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32;
    if (HAL_SPI_Init(&hspi1) != HAL_OK)
    {
        /* Initialization Error */
        Error_Handler();
        return -1;
    }

    return 0;
}

#if defined(EVE_QSPI_ENABLE)
int MCU_SetSPIMode(uint8_t mode)
{
    /* QSPI Configuration */
    #error EVE_QSPI_ENABLE is not supported by the PLATFORM_STM32 port
    return -1;
}
#endif // defined(EVE_QSPI_ENABLE)

inline void MCU_CSlow(void)
{
    HAL_GPIO_WritePin(config_gpio, config_pin_cs, GPIO_PIN_RESET);
    // Perform a very short delay
    __nop();
}

inline void MCU_CShigh(void)
{
    HAL_GPIO_WritePin(config_gpio, config_pin_cs, GPIO_PIN_SET);
    // Perform a very short delay
    __nop();
}

inline void MCU_PDlow(void)
{
    // PD# line low
    HAL_GPIO_WritePin(config_gpio, config_pin_pd, GPIO_PIN_RESET);
}

inline void MCU_PDhigh(void)
{
    // PD# line high
    HAL_GPIO_WritePin(config_gpio, config_pin_pd, GPIO_PIN_SET);
}

int MCU_Int(void) 
{
    return (int)HAL_GPIO_ReadPin(config_gpio, config_pin_int);
}

uint8_t MCU_SPIReadWrite8(uint8_t DataToWrite)
{
    uint8_t DataRead;
    uint8_t TxBuffer;
    
    TxBuffer = DataToWrite;
        
    // Note: This platform is LITTLE_ENDIAN. 
    // Buffer transmits/receives of integers will be little endian.
    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 1, HAL_MAX_DELAY);

    // Note that this call to the STM32 HAL returns a status value which can be checked as shown below in order
    // to make the application more robust
#if 0
    switch(HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)TxBuffer, (uint8_t *)DataRead, 1, HAL_MAX_DELAY))
    {
    case HAL_OK:
      /* Communication is completed */
    case HAL_TIMEOUT:
      /* A Timeout Occur */
      /* Call Timeout Handler */
      Timeout_Error_Handler();
      break;
      /* An Error Occur */
    case HAL_ERROR:
      /* Call Timeout Handler */
      Error_Handler();
      break;
    default:
      break;
  }
#endif
       
    return DataRead;
}

uint16_t MCU_SPIReadWrite16(uint16_t DataToWrite)
{
    uint16_t DataRead;
    uint16_t TxBuffer = DataToWrite;

    // Note: This platform is LITTLE_ENDIAN. 
    // Buffer transmits/receives of integers will be little endian.
    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 2, HAL_MAX_DELAY);

    return MCU_le16toh(DataRead);
}

uint32_t MCU_SPIReadWrite24(uint32_t DataToWrite)
{
    uint32_t DataRead;
    uint32_t TxBuffer = DataToWrite;
    
    // Note: This platform is LITTLE_ENDIAN. 
    // Buffer transmits/receives of integers will be little endian.
    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 3, HAL_MAX_DELAY);

    return MCU_le32toh(DataRead);
}

uint32_t MCU_SPIReadWrite32(uint32_t DataToWrite)
{
    uint32_t DataRead;
    uint32_t TxBuffer = DataToWrite;

    // Note: This platform is LITTLE_ENDIAN. 
    // Buffer transmits/receives of integers will be little endian.
    HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)&TxBuffer, (uint8_t *)&DataRead, 4, HAL_MAX_DELAY);
 
    return MCU_le32toh(DataRead);
}

void MCU_Delay_20ms(void)
{
    HAL_Delay(20);
}

void MCU_Delay_500ms(void)
{
    HAL_Delay(500);
}

uint32_t MCU_Time_ms(void)
{
    return HAL_GetTick();
}

// --------------------- SPI Send and Receive ----------------------------------

uint8_t MCU_SPIRead8(void)
{
    uint8_t DataRead = 0;

    DataRead = MCU_SPIReadWrite8(0);
    
    return DataRead;
}

void MCU_SPIWrite8(uint8_t DataToWrite)
{
    MCU_SPIReadWrite8(DataToWrite);
}

uint16_t MCU_SPIRead16(void)
{
    uint16_t DataRead = 0;

    DataRead = MCU_SPIReadWrite16(0);

    return MCU_le16toh(DataRead);
}

void MCU_SPIWrite16(uint16_t DataToWrite)
{
    MCU_SPIReadWrite16(DataToWrite);
}

void MCU_SPIWrite24(uint32_t DataToWrite)
{
    MCU_SPIReadWrite24(DataToWrite);
}

uint32_t MCU_SPIRead32(void)
{
    uint32_t DataRead = 0;

    DataRead = MCU_SPIReadWrite32(0);

    return MCU_le32toh(DataRead);
}

void MCU_SPIWrite32(uint32_t DataToWrite)
{
    MCU_SPIReadWrite32(DataToWrite);
}

void MCU_SPIWrite(const uint8_t *DataToWrite, uint32_t length)
{
    uint32_t DataPointer = 0;
    DataPointer = 0;

    while(DataPointer < length)
    {
        MCU_SPIWrite8(DataToWrite[DataPointer]);  // Send data byte-by-byte from array
        DataPointer += sizeof(uint8_t);
    }
}

void MCU_SPIRead(uint8_t *DataToRead, uint32_t length)
{
    uint16_t DataPointer = 0;
    DataPointer = 0;

    while(DataPointer < length)
    {
        DataToRead[DataPointer] = MCU_SPIRead8();  // Send data byte-by-byte from array
        DataPointer += sizeof(uint8_t);
    }
}

// Note: This platform is LITTLE_ENDIAN. 
// Endian-swaps are made using bswaps - there is no endian.h header.

uint16_t MCU_htobe16 (uint16_t h)
{
    return bswap16(h);
}

uint32_t MCU_htobe32 (uint32_t h)
{
    return bswap32(h);
}

uint16_t MCU_htole16 (uint16_t h)
{
    return h;
}

uint32_t MCU_htole32 (uint32_t h)
{
    return h;
}

uint16_t MCU_be16toh (uint16_t h)
{
    return bswap16(h); 
}

uint32_t MCU_be32toh (uint32_t h)
{
    return bswap32(h); 
}

uint16_t MCU_le16toh (uint16_t h)
{
    return h;
}

uint32_t MCU_le32toh (uint32_t h)
{
    return h;
}

/* EVE MCU END */

#endif /* defined (PLATFORM_STM32) */
