/**
 * @file EVE_MCU_STM32CUBE.c
 * @details MCU-specific code for controlling EVE on STM32 devices.
 */
/*
 * ============================================================================
 * (C) Copyright,  Bridgetek Pte. Ltd.
 * ============================================================================
 *
 * This source code ("the Software") is provided by Bridgetek Pte Ltd
 * ("Bridgetek") subject to the licence terms set out
 * http://brtchip.com/BRTSourceCodeLicenseAgreement/ ("the Licence Terms").
 * You must read the Licence Terms before downloading or using the Software.
 * By installing or using the Software you agree to the Licence Terms. If you
 * do not agree to the Licence Terms then do not download or use the Software.
 *
 * Without prejudice to the Licence Terms, here is a summary of some of the key
 * terms of the Licence Terms (and in the event of any conflict between this
 * summary and the Licence Terms then the text of the Licence Terms will
 * prevail).
 *
 * The Software is provided "as is".
 * There are no warranties (or similar) in relation to the quality of the
 * Software. You use it at your own risk.
 * The Software should not be used in, or for, any medical device, system or
 * appliance. There are exclusions of Bridgetek liability for certain types of loss
 * such as: special loss or damage; incidental loss or damage; indirect or
 * consequential loss or damage; loss of income; loss of business; loss of
 * profits; loss of revenue; loss of contracts; business interruption; loss of
 * the use of money or anticipated savings; loss of information; loss of
 * opportunity; loss of goodwill or reputation; and/or loss of, damage to or
 * corruption of data.
 * There is a monetary cap on Bridgetek's liability.
 * The Software may have subsequently been amended by another user and then
 * distributed by that other user ("Adapted Software").  If so that user may
 * have additional licence terms that apply to those amendments. However, Bridgetek
 * has no liability in relation to those amendments.
 * ============================================================================
 */

// Guard against being used for incorrect platform or architecture.
#if defined(PLATFORM_STM32_CUBE)

/* EVE MCU HEADER */

/* Header for STM32 (generated by STMCubeMX) */
#include <main.h>

/* QUADSPI Enabled in STM32CubeMX for the STM32 */
/* Platform macro MUST include the handle of the interface. */
#if PLATFORM_STM32_CUBE == 4

/* Display message to indicate quad channel SPI selected */
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)
#pragma message ("STM32Cube Quad Channel SPI controller enabled on channel " STR(PLATFORM_STM32_CUBE_CHANNEL))


#include <stdint.h> // for Uint8/16/32 and Int8/16/32 data types
#include <string.h>
#include <stdlib.h>

/* Include functions for EVE-MCU-Dev library MCU layer */
#include <MCU.h>
/* Include EVE-MCU-Dev library debug macros */
#include "EVE_debug.h"

#include "quadspi.h"

/* Define a "safe" prescaler for QUADSPI. This is used during initialisation
 * and must be below 11 MHz. The fastest speed is usually in the order of
 * 120 to 240 MHz. So a prescalar of 64 will be safely within that limit.
 * The speed will be set to the full speed after initialisation. */
#define QSPI_CLK_DIV (64 - 1)

/* EVE MCU HEADER END */

/* EVE MCU */

// This is the STM32 platform specific section and contains the functions which
// enable the GPIO and SPI interfaces.

#if defined(EVE_QSPI_ENABLE)
#pragma message ("SPI Mode: Quad channel")
#if IS_EVE_API(1)
#error Quad SPI is not supported on EVE API 1 (FT80x)
#endif
#else
#pragma message ("SPI Mode: Single channel")
#endif

/* SPI handler declaration */
/* There is only one QUADSPI channel available. */
extern QSPI_HandleTypeDef hqspi;

/* Transfers are "chunked" to the EVE by the HAL.
 * This buffer is large enough to receive one chunk of
 * data and transmit it in one go. If it cannot be
 * sent in one go then the write address may not be
 * valid on subsequent packets.
 */
#define MCU_BUFFER_SIZE (HAL_MAX_CHUNK_SIZE)
static uint8_t *MCU_buffer;
static uint16_t MCU_bufferLen;

/* Forward declaration */
#if 0
static void Error_Handler(void);
#endif

/* Default QuadSPI off. */
static int isQuadSPI = 0;

int MCU_Init(void)
{
    MCU_buffer = malloc(MCU_BUFFER_SIZE);
    if (MCU_buffer == NULL)
    {
        EVE_DEBUG_ERROR("QSPI Setup malloc failed\n");
        return -1;
    }

    MCU_bufferLen = 0;

    /* Set the QUADSPI speed to a safe minimum. It must be
     * under 11 MHz but 1 MHz is very safe.
     * Use the "safe" prescaler to get a safe clock for SPI
     * during initialisation.
     */
    hqspi.Init.ClockPrescaler = QSPI_CLK_DIV;
    if (HAL_QSPI_Init(&hqspi) != HAL_OK)
    {
      Error_Handler();
      return -1;
    }

    return 0;
}

int MCU_Deinit(void)
{
    /* Leave EVE in a safe state. */
    MCU_CShigh();
    MCU_PDlow();

    /* Disable SPI peripheral. */
    if (HAL_QSPI_DeInit(&hqspi) != HAL_OK)
    {
        return -1;
    }

    if (MCU_buffer)
    {
        free(MCU_buffer);
        MCU_buffer = NULL;
    }

    return 0;
}

int MCU_Setup(void)
{
    return 0;
}

#if defined(EVE_QSPI_ENABLE)
int MCU_SetSPIMode(uint8_t mode)
{
    if (mode == EVE_SPI_SINGLE_CHANNEL)
    {
        isQuadSPI= 0;
    }
    else if (mode == EVE_SPI_QUAD_CHANNEL)
    {
        /* QSPI Configuration */
        /* Increase SPI speed after initialisation is complete.
        * See the notes for MCU_SPI_TIMEOUT in the MCU.h file.
        * This will set the QUADSPI to maximum speed configured
        * in STM32CubeMX.
        * This can be a maximum of 60 MHz for BT820, or 25 MHz
        * on FT81x, BT88x, BT81x. */
        MX_QUADSPI_Init();

        isQuadSPI = 1;
    }
    else
    {
        return -1;
    }

    return 0;
}
#endif /* defined(EVE_QSPI_ENABLE) */

/* Send data in the write buffer and read in bytes from the QSPI. */
static HAL_StatusTypeDef MCU_multi_transfer(uint8_t *DataToRead, uint32_t len)
{
    QSPI_CommandTypeDef sCommand = {0};
    HAL_StatusTypeDef status;

    /* There will be only read OR write operations to perform. */
    /* If the write buffer length is greater than 4 bytes for BT82x or 
     * 3 bytes for previous devices then we are writing. */
    if ((MCU_bufferLen > 0) && (len == 0))
    {
    	/* Write the contents of the buffer to the EVE device.
    	 * The address is in big-endian format in the first 4 bytes for
    	 * EVE API 5 and the first 3 for previous generations.
    	 */
        sCommand.InstructionMode   = QSPI_INSTRUCTION_NONE;
        sCommand.AddressMode       = QSPI_ADDRESS_NONE;
        sCommand.AddressSize       = QSPI_ADDRESS_32_BITS;
        if (isQuadSPI == 0)
        {
            sCommand.DataMode          = QSPI_DATA_1_LINE;
        }
        else
        {
            sCommand.DataMode          = QSPI_DATA_4_LINES;
        }
		sCommand.NbData            = MCU_bufferLen;
        sCommand.DummyCycles       = 0;
        sCommand.DdrMode           = QSPI_DDR_MODE_DISABLE;
        sCommand.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY;
        sCommand.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;

        status = HAL_QSPI_Command(&hqspi, &sCommand, HAL_MAX_DELAY);
        if (status != HAL_OK)
        {
            EVE_DEBUG_PRINTF("QSPI command sending error in QSPI_Transmit...\n");
            return status;
        }
        else
        {
			status = HAL_QSPI_Transmit(&hqspi, MCU_buffer, HAL_MAX_DELAY);
			if (status != HAL_OK)
			{
				EVE_DEBUG_PRINTF("QSPI Transmit error in QSPI_Transmit...\n");
				return status;
			}
		}
        MCU_bufferLen = 0;
    }
    else if ((MCU_bufferLen > 0) && (len > 0))
    {
    	/* Read from the EVE device to the buffer in the parameters.
    	 * The address is previously set in big-endian format in the first 4
    	 * bytes of the transmit buffer for all generations.
    	 */
        /* Reconstruct the big-endian address from the MCU_buffer array */
        uint32_t addr = (MCU_buffer[0] << 24) | (MCU_buffer[1] << 8) | (MCU_buffer[2] << 8) | (MCU_buffer[3] << 0);

        sCommand.InstructionMode   = QSPI_INSTRUCTION_NONE;
        sCommand.AddressSize       = QSPI_ADDRESS_32_BITS;
        sCommand.Address           = addr;

        if (isQuadSPI == 0)
        {
            sCommand.AddressMode       = QSPI_ADDRESS_1_LINE;
            sCommand.DataMode          = QSPI_DATA_1_LINE;
        }
        else
        {
            sCommand.AddressMode       = QSPI_ADDRESS_4_LINES;
            sCommand.DataMode          = QSPI_DATA_4_LINES;
        }
        sCommand.NbData            = len;
        sCommand.DummyCycles       = 0;
        sCommand.DdrMode           = QSPI_DDR_MODE_DISABLE;
        sCommand.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY;
        sCommand.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;

        status = HAL_QSPI_Command(&hqspi, &sCommand, HAL_MAX_DELAY);
        if (status != HAL_OK)
        {
            EVE_DEBUG_PRINTF("QSPI command sending error in rdBuffer...\n");
            return status;
        }
        else
        {
			status = HAL_QSPI_Receive(&hqspi, DataToRead, HAL_MAX_DELAY);
			if (status != HAL_OK)
			{
				EVE_DEBUG_PRINTF("QSPI receive error in rdBuffer...\n");
				return status;
			}
        }
        MCU_bufferLen = 0;
    }

    return HAL_OK;
}

static int MCU_receive_buffer(uint8_t *DataToRead, uint32_t len, int end)
{
    HAL_StatusTypeDef status = HAL_OK;

    status = MCU_multi_transfer(DataToRead, len);
    if (status != HAL_OK)
	{
    	*DataToRead = 0;
    }

    return status;
}

static int MCU_append_buffer(const uint8_t *buffer, uint16_t length, int end)
{
    HAL_StatusTypeDef status = HAL_OK;
    int i = MCU_bufferLen;
    int j = 0;
    int plength;

    while (j < length)
    {
        plength = length - j;
        
        if (plength + MCU_bufferLen >= MCU_BUFFER_SIZE)
            plength = MCU_BUFFER_SIZE - MCU_bufferLen;
        
        /* NOTE: memcpy is used here as the libft4222 is not generally 
         * used for embedded systems.
         */
        memcpy(&MCU_buffer[i], &buffer[j], plength);
        j += plength;
        i += plength;
        MCU_bufferLen += plength;
        if (MCU_bufferLen >= MCU_BUFFER_SIZE)
        {
            status = MCU_multi_transfer(NULL, 0);

            if (status != HAL_OK)
			{
            	MCU_bufferLen = 0;
            	break;
            }
            /* Keep the previous write address in the transmit buffer if we are not
                * ending this transfer. */
            if (end == 0)
            {
                /* Refill buffer after address. */
#if IS_EVE_API(1, 2, 3, 4) /* Different write addressing method on BT82x */
                /* 24 bit write address followed by data */
                i = 3;
                MCU_bufferLen = 3;
#else
                /* 32 bit write address followed by data */
                i = 4;
                MCU_bufferLen = 4;
#endif
            }
        }
    }

    return status;
}

inline void MCU_CSlow(void)
{
    // CS# line low
    // Perform a very short delay
    __NOP();
}

inline void MCU_CShigh(void)
{
    // CS# line high
    MCU_multi_transfer(NULL, 0);
    // Perform a very short delay
    __NOP();
}

uint8_t MCU_SPIRead8(void)
{
    HAL_StatusTypeDef status;
    uint8_t DataRead = 0;

    status = MCU_receive_buffer((uint8_t *)&DataRead, 1, 0);
    if (HAL_OK != status)
    {
         // QUADSPI master read failed
        EVE_DEBUG_ERROR("MCU_SPIRead8 failed %d\n", status);
        DataRead = 0;
    }
 
    return DataRead;
}

void MCU_SPIWrite8(uint8_t DataToWrite)
{
    MCU_append_buffer((uint8_t *)&DataToWrite, 1, 0);
}

uint16_t MCU_SPIRead16(void)
{
    HAL_StatusTypeDef status;
    uint16_t DataRead;

    status = MCU_receive_buffer((uint8_t *)&DataRead, 2, 0);
    if (HAL_OK != status)
    {
        // QUADSPI master read failed
        EVE_DEBUG_ERROR("MCU_SPIRead16 failed %d\n", status);
        DataRead = 0;
    }

    return DataRead;
}

void MCU_SPIWrite16(uint16_t DataToWrite)
{
    MCU_append_buffer((uint8_t *)&DataToWrite, 2, 0);
}

void MCU_SPIWrite24(uint32_t DataToWrite)
{
    MCU_append_buffer((uint8_t *)&DataToWrite, 3, 0);
}

uint32_t MCU_SPIRead32(void)
{
    HAL_StatusTypeDef status;
    uint32_t DataRead = 0;

    status = MCU_receive_buffer((uint8_t *)&DataRead, 4, 0);
    if (HAL_OK != status)
    {
        // QUADSPI master read failed
        EVE_DEBUG_ERROR("MCU_SPIRead32 failed %d\n", status);
        DataRead = 0;
    }

    return DataRead;
}

void MCU_SPIWrite32(uint32_t DataToWrite)
{
    MCU_append_buffer((uint8_t *)&DataToWrite, 4, 0);
}

void MCU_SPIRead(uint8_t *DataToRead, uint32_t length)
{
    HAL_StatusTypeDef status;

    status = MCU_receive_buffer((uint8_t *)DataToRead, length, 0);
    if (HAL_OK != status)
    {
        // QUADSPI master read failed
        EVE_DEBUG_ERROR("MCU_SPIRead failed %d\n", status);
    }
}

void MCU_SPIWrite(const uint8_t *DataToWrite, uint32_t length)
{
    MCU_append_buffer(DataToWrite, length, 0);
}

/* EVE MCU END */

#endif /* defined(HAL_QSPI_MODULE_ENABLED) */

#endif /* defined (PLATFORM_STM32_CUBE) */
